export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const SUBSCRIBE_CONTACTS = 'SUBSCRIBE_CONTACTS';

export const SUBSCRIBE_CONVERSATIONS_LIST = 'SUBSCRIBE_CONVERSATIONS_LIST';
