export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const SUBSCRIBE_CONTACTS = 'SUBSCRIBE_CONTACTS';
export const UNSUBSCRIBE_CONTACTS = 'UNSUBSCRIBE_CONTACTS';
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';

export const SUBSCRIBE_CONVERSATIONS_LIST = 'SUBSCRIBE_CONVERSATIONS_LIST';
export const UPDATE_CONVERSATIONS_LIST = 'UPDATE_CONVERSATIONS_LIST';
export const UNSUBSCRIBE_CONVERSATIONS_LIST = 'UNSUBSCRIBE_CONVERSATIONS_LIST';
